#!/usr/bin/env bash

set -e #-xx
testFile="${TRAVIS_BUILD_DIR}/test.tmp"

git log --word-diff=porcelain -1 -p  -- submit_here/hosts.txt | \
  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "$testFile"

git log --word-diff=porcelain -1 -p  -- submit_here/mobile.txt | \
  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "$testFile"

git log --word-diff=porcelain -1 -p  -- submit_here/snuff.txt | \
  grep -e "^+" | cut -d "+" -f2 | grep -vE "^(#|$)" >> "$testFile"

RunFunceble () {

    cd "${TRAVIS_BUILD_DIR}/dev-tools" || exit 1

    hash PyFunceble

	printf "\n\tYou are running with RunFunceble\n\n"

	PyFunceble --version

        PyFunceble --ci -m -p "$(nproc --ignore=1)" \
	        -ex -db --database-type mariadb \
            --autosave-minutes 38 --share-logs --idna \
            --hierarchical --ci-branch "${TRAVIS_BRANCH}" \
            --syntax -f "${testFile}"

}
RunFunceble

exit ${?}


# Copyright: https://www.mypdns.org/
# Content: https://www.mypdns.org/p/Spirillen/
# Source: https://www.mypdns.org/source/PornHosts/
# License: https://www.mypdns.org/w/License
# License Comment: GNU AGPLv3, MODIFIED FOR NON COMMERCIAL USE
#
# License in short:
# You are free to copy and distribute this file for non-commercial uses,
# as long the original URL and attribution is included.
#
# Please forward any additions, corrections or comments by logging an
# issue at https://www.mypdns.org/maniphest/

# Execute this script as bash porn/porn.sh from the root folder
